[package]
name = "web"
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server = {path = "../server"}